SET SERVEROUTPUT ON; 
CREATE OR REPLACE 
PROCEDURE listDependent
AS 
    CURSOR dc IS 
        SELECT * FROM dependent;
    d dc%ROWTYPE;
BEGIN
    FOR d in dc LOOP
        DBMS_OUTPUT.PUT_LINE(d.DEPENDENT_NAME ||' '||d.RELATIONSHIP);
    END LOOP;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;